[package]
name = "inventory_control_system"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
chrono = "0.4.38"
