[package]
name = "inventory_control_system"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
chrono = "0.4.38"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls"] }
dotenv = "0.15.0"
tokio = { version = "1.37.0", features = ["full"] }
